<p>At the Department of Communications, we aim to lead by example. This means being at the cutting edge of information and communications technology (ICT) and helping our staff to work flexibly anywhere, anytime. If we can do it, everyone can.</p>
<p>In May 2015, we became the first Commonwealth department to move our entire IT infrastructure to a secure cloud service. We plan to finish the transition by October 2015.</p>
<p>We are leading the move away from the traditional capital-intensive ICT delivery model to adopting a secure government cloud platform. This transition will give us a sustainable, cost effective and scalable &lsquo;pay as you use&rsquo; consumption model, in line with the Government&rsquo;s Cloud First directive. The service will allow us to scale our IT capability and capacity to meet changing demands, meaning IT services will be delivered more effectively and at a reduced cost.</p>
<p>We want to have the organisational capacity, capability and culture to support a high performing workforce and deliver outcomes for government. We have realised our goal of enabling staff to work smarter, be more productive and operate in ways that support greater collaboration and engagement. We now have an environment where staff have access to the latest technology, and the flexibility and agility to seamlessly interact with anyone, anywhere, at anytime.</p>
<p>A sophisticated working environment sees us operate within a managed wireless network where laptops are replacing paper and pens, staff are able to video call in to meetings from their laptops and take part while staying connected to their applications and information. They can also seamlessly undock their laptops from their desks to collaborate with colleagues in open spaces or keep working from home.</p>
<p>We want to be distinguished by our people and our collaborative culture. In February 2015, this led to the launch of the Digital Literacy Training Programme to help us as a department be digitally literate. This means:</p>
<ul>
    <li>Being digitally curious&mdash;exploring and trying new digital things.</li>
    <li>Being digitally effective&mdash;knowing how to use applications and platforms effectively in the workplace.</li>
    <li>Being digitally confident&mdash;to troubleshoot commonly used applications and platforms ourselves.</li>
</ul>
<p>We know that by being more digitally literate we will both enhance our productivity and improve our capability to make the most of available technologies.</p>
<p>The Digital Literacy Training Programme includes a series of short workshops, videos and the Lynda.com portal to help build confidence, skills and knowledge of applications and platforms in the digital world.&nbsp;Staff can identify what topics they are interested in from the intranet training calendar and schedule training sessions on topics such as Facebook, Twitter, RSS Feeds, YouTube and writing online content. We also invite guest speakers to showcase new technologies or new digital initiatives.&nbsp;</p>
<p>This year we also started to provide a <em>seamless digital experience to stakeholders</em>. Two examples of this are our 2013&ndash;14 Annual Report and the redeveloped <a href="https://www.communications.gov.au/">communications.gov.au</a> website.</p>
<p>The creation of a digital version of our 2013&ndash;14 Annual Report was centred on creating relevant, meaningful content that our stakeholders, industry and the community could better engage with. For the first time we also prepared a summary version of the document that could be downloaded as an app.</p>
<p>We were very proud of the end result and it was recognised with a Gold award in the Institute of Public Administration online reports category for large/medium <em>Financial Management and Accountability Act 1997 </em>Agencies. The accompanying comments noted &lsquo;this online report seeks to reach new standards in the use of digital technology&rsquo;.</p>
<p>Our flagship digital project in 2014<em>&ndash;</em>15 was the redevelopment of the <a href="https://www.communications.gov.au/">communications.gov.au</a> website in the GovCMS platform: the whole-of-government content management system.</p>
<p>GovCMS has allowed us to build on an open source product, reaping the rewards of cloud hosting and contributing back to a new government digital web community. The redevelopment, which was directed by user needs, features a &lsquo;Have Your Say&rsquo; policy consultation page that will allow for greater engagement on policy development by industry, stakeholders and the public.</p>
<p>The project saw the amalgamation of several standalone programme sites, which has minimised our digital footprint and ensured a consistent and unified user experience. </p>

<p><a href="https://www.communications.gov.au/" class="caseStudy__link" title="Go to the Department of Communications website">www.communications.gov.au</a></p>

<p><img src="/2015/assets/images/content/caseStudies/comms-website.jpg" alt="Image of the Department of Communications website" /></p>